.TH "/home/emeric/projets/CBay/sources/ Directory Reference" 3 "Thu Feb 12 2015" "Version BEEP - 0.1a" "CBay" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/emeric/projets/CBay/sources/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient\&.c\fP"
.br
.ti -1c
.RI "file \fBclient\&.h\fP"
.br
.RI "\fIThis file provides function for a BEEP client\&. It also contains fonction to send data using other methods than connect (typically GET, PUT and DELETE) or function to split and extract data from incoming answer from the server\&. \fP"
.ti -1c
.RI "file \fBdefines\&.h\fP"
.br
.RI "\fIThis file defines all constants\&. \fP"
.ti -1c
.RI "file \fBinterfaceClient\&.c\fP"
.br
.ti -1c
.RI "file \fBinterfaceClient\&.h\fP"
.br
.RI "\fIThis file provides the main function to interact with the user like displaying menus or menu choices\&. Nearly all the user's input are taken with those functions\&. The only exception is for the account and the object creation\&. \fP"
.ti -1c
.RI "file \fBmainClient\&.c\fP"
.br
.ti -1c
.RI "file \fBmainServeur\&.c\fP"
.br
.ti -1c
.RI "file \fBserveur\&.c\fP"
.br
.ti -1c
.RI "file \fBserveur\&.h\fP"
.br
.RI "\fIThis file provides BEEP server functions This file provides some usual functions for a server like init, reception and emission\&. It also contains some other derivated functions to test and play with received requests plus response making functions like status line and header fields answering \&. \fP"
.ti -1c
.RI "file \fBstructures\&.c\fP"
.br
.ti -1c
.RI "file \fBstructures\&.h\fP"
.br
.RI "\fIthis file provides functions for data manipulation This file provides data structures and usual associated functions\&. There is also utilities like clenBuffer\&. \fP"
.in -1c
