.TH "ConfidentialIDS" 3 "Thu Feb 12 2015" "CBay" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfidentialIDS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBid\fP"
.br
.ti -1c
.RI "char \fBlogin\fP [USERACCOUNT_LOGIN_LENGTH]"
.br
.ti -1c
.RI "char \fBpassword\fP [USERACCOUNT_PASSWORD_LENGTH]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CBay from the source code\&.
