.TH "ObjectBid" 3 "Thu Feb 12 2015" "Version BEEP - 0.1a" "CBay" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectBid \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBid\fP"
.br
.ti -1c
.RI "char \fBname\fP [\fBOBJECTBID_NAME_LENGTH\fP]"
.br
.ti -1c
.RI "float \fBbasePrice\fP"
.br
.ti -1c
.RI "char \fBdescription\fP [\fBOBJECTBID_DESCRIPTION_LENGTH\fP]"
.br
.ti -1c
.RI "long int \fBidVendor\fP"
.br
.ti -1c
.RI "long int \fBstartTime\fP"
.br
.ti -1c
.RI "long int \fBendTime\fP"
.br
.ti -1c
.RI "char \fBadress\fP [\fBOBJECTBID_ADRESS_LENGTH\fP]"
.br
.ti -1c
.RI "float \fBcurrentBidPrice\fP"
.br
.ti -1c
.RI "long int \fBcurrentBidIdBuyer\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char adress[\fBOBJECTBID_ADRESS_LENGTH\fP]"

.SS "float basePrice"

.SS "long int currentBidIdBuyer"

.SS "float currentBidPrice"

.SS "char description[\fBOBJECTBID_DESCRIPTION_LENGTH\fP]"

.SS "long int endTime"

.SS "long int id"

.SS "long int idVendor"

.SS "char name[\fBOBJECTBID_NAME_LENGTH\fP]"

.SS "long int startTime"


.SH "Author"
.PP 
Generated automatically by Doxygen for CBay from the source code\&.
