.TH "ObjectBid" 3 "Thu Feb 12 2015" "CBay" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectBid \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBid\fP"
.br
.ti -1c
.RI "char \fBname\fP [OBJECTBID_NAME_LENGTH]"
.br
.ti -1c
.RI "float \fBbasePrice\fP"
.br
.ti -1c
.RI "char \fBdescription\fP [OBJECTBID_DESCRIPTION_LENGTH]"
.br
.ti -1c
.RI "long int \fBidVendor\fP"
.br
.ti -1c
.RI "long int \fBstartTime\fP"
.br
.ti -1c
.RI "long int \fBendTime\fP"
.br
.ti -1c
.RI "char \fBadress\fP [OBJECTBID_ADRESS_LENGTH]"
.br
.ti -1c
.RI "float \fBcurrentBidPrice\fP"
.br
.ti -1c
.RI "long int \fBcurrentBidIdBuyer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CBay from the source code\&.
