.TH "UserAccount" 3 "Thu Feb 12 2015" "CBay" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserAccount \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtype\fP"
.br
.ti -1c
.RI "long int \fBid\fP"
.br
.ti -1c
.RI "char \fBname\fP [USERACCOUNT_NAME_LENGTH]"
.br
.ti -1c
.RI "char \fBlastname\fP [USERACCOUNT_LASTNAME_LENGTH]"
.br
.ti -1c
.RI "char \fBadress\fP [USERACCOUNT_ADRESS_LENGTH]"
.br
.ti -1c
.RI "char \fBmail\fP [USERACCOUNT_MAIL_LENGTH]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CBay from the source code\&.
